ppo_NatureCNN_graclip05_b32_h512_lr14_obs84: &ppo_NatureCNN_graclip05_b32_h512_lr14_obs84
        nbr_frame_stacking: 1
        observation_resize_dim: 84
        discount: 0.99
        use_gae: True
        use_cuda: True
        gae_tau: 0.95
        entropy_weight: 0.02
        gradient_clip: 0.5
        optimization_epochs: 10
        mini_batch_size: 32
        ppo_ratio_clip: 0.2
        learning_rate: 1.e-4
        adam_eps: 1.0e-8
        #nbr_actor: 4
        horizon: 512
        phi_arch: 'CNN' #'MLP' #'CNN-GRU-RNN'
        actor_arch: 'MLP'
        critic_arch: 'MLP'
        
        # Phi Body: Nature:
        phi_arch_channels: [32, 64, 64] # [32, 64, 32]
        phi_arch_kernels: [8, 4, 3]
        phi_arch_strides: [4, 2, 1]
        phi_arch_paddings: [1, 1, 1]
        phi_arch_feature_dim: 512 #vae_nbr_latent_dim']#512
        phi_arch_hidden_units: [512,]

        # BetaVAE:
        use_vae: False
        vae_weight: 1e0
        vae_nbr_latent_dim: 128
        vae_decoder_nbr_layer: 3#4
        vae_decoder_conv_dim: 128
        
        cnn_encoder_feature_dim: 128 #vae_nbr_latent_dim
        
        vae_beta: 1e2
        vae_max_capacity: 1e2
        vae_nbr_epoch_till_max_capacity: 20
        vae_constrainedEncoding: False
        vae_tc_discriminator_hidden_units: [256,256,256,256,2] #tuple([2*cnn_encoder_feature_dim']]*4+[2])
        
        # Random Network Distillation:
        use_random_network_distillation: False
        intrinsic_discount: 0.99
        rnd_loss_int_ratio: 0.5
        rnd_obs_clip: 5
        rnd_non_episodic_int_r: True
        rnd_update_period_running_meanstd_int_reward: 1.e5
        rnd_update_period_running_meanstd_obs: 1.e5 #rnd_update_period_running_meanstd_int_reward
        # RND Convolutional Architecture:
        rnd_arch: 'CNN'
        rnd_arch_channels: [32, 64, 64]
        rnd_arch_kernels: [8, 4, 3]
        rnd_arch_strides: [4, 2, 1]
        rnd_arch_paddings: [0, 1, 1]
        rnd_arch_feature_dim: 512
        # RND Fully-Connected Architecture:
        #rnd_feature_net_fc_arch_hidden_units: (128, 64)


ppo_DQNCNN_graclip05_ep3_b32_h128_lr254_obs84: &ppo_DQNCNN_graclip05_ep3_b32_h128_lr254_obs84
        nbr_frame_stacking: 1
        observation_resize_dim: 84
        discount: 0.99
        use_gae: True
        use_cuda: True
        gae_tau: 0.95
        entropy_weight: 0.01
        gradient_clip: 0.5
        optimization_epochs: 3
        mini_batch_size: 32
        ppo_ratio_clip: 0.2
        learning_rate: 2.5e-4
        adam_eps: 1.0e-8
        #nbr_actor: 4
        horizon: 128
        phi_arch: 'CNN' #'MLP' #'CNN-GRU-RNN'
        actor_arch: 'MLP'
        critic_arch: 'MLP'
        
        # Phi Body: Nature:
        phi_arch_channels: [16, 32]
        phi_arch_kernels: [8, 4]
        phi_arch_strides: [4, 2]
        phi_arch_paddings: [1, 1]
        phi_arch_feature_dim: 256 #vae_nbr_latent_dim']#512
        phi_arch_hidden_units: [256,]

        # BetaVAE:
        use_vae: False
        vae_weight: 1e0
        vae_nbr_latent_dim: 128
        vae_decoder_nbr_layer: 3#4
        vae_decoder_conv_dim: 128
        
        cnn_encoder_feature_dim: 128 #vae_nbr_latent_dim
        
        vae_beta: 1e2
        vae_max_capacity: 1e2
        vae_nbr_epoch_till_max_capacity: 20
        vae_constrainedEncoding: False
        vae_tc_discriminator_hidden_units: [256,256,256,256,2] #tuple([2*cnn_encoder_feature_dim']]*4+[2])
        
        # Random Network Distillation:
        use_random_network_distillation: False
        intrinsic_discount: 0.99
        rnd_loss_int_ratio: 0.5
        rnd_obs_clip: 5
        rnd_non_episodic_int_r: True
        rnd_update_period_running_meanstd_int_reward: 1.e5
        rnd_update_period_running_meanstd_obs: 1.e5 #rnd_update_period_running_meanstd_int_reward
        # RND Convolutional Architecture:
        rnd_arch: 'CNN'
        rnd_arch_channels: [32, 64, 64]
        rnd_arch_kernels: [8, 4, 3]
        rnd_arch_strides: [4, 2, 1]
        rnd_arch_paddings: [0, 1, 1]
        rnd_arch_feature_dim: 512
        # RND Fully-Connected Architecture:
        #rnd_feature_net_fc_arch_hidden_units: (128, 64)


experiment:
    tasks: [{'env-id': 'QbertNoFrameskip-v4',
            #{'env-id': 'SeaquestNoFrameskip-v4',
            #{'env-id': 'BreakoutNoFrameskip-v4',
             'agent-id': 'ppo_midloopOldPred_paper_ep3_clip0.1_gradclip0.5_b32_lr2.5e-4_ent0.02_8actors_NoNormR_Sk1',
             'nbr_actors': 8,
             'nbr_frame_skipping': 1,
             'nbr_frame_stacking': 4,
             'observation_resize_dim': 84
             },
            #{'env-id': 'MiniWorld-OneRoomS6Fast-v0',
            # 'agent-id': 'ppo_scnn_lr3_obs84_initXavier',
            # 'nbr_actors': 32,
            # 'nbr_frame_skipping': 4,
            # 'nbr_frame_stacking': 4,
            # 'observation_resize_dim': 84
            # },
            #{'env-id': 'SeaquestNoFrameskip-v4',
            # 'agent-id': 'ppo',
            # 'nbr_actors': 32,
            # 'nbr_frame_skipping': 4,
            # 'nbr_frame_stacking': 4,
            # 'observation_resize_dim': 64
            # },
            # {'env-id': 'Pong-v0',
            # 'agent-id': 'ppo',
            # 'nbr_actors': 32,
            # 'nbr_frame_skipping': 4,
            # 'nbr_frame_stacking': 4,
            # 'observation_resize_dim': 64
            # }
            ]
    experiment_id: 'benchmark-test'
    benchmarking_episodes: 10
    train_observation_budget: 1.e7
    seed: 69

agents:
    ppo_NatureCNN_graclip05_b32_h512_lr14_obs84_2actors:
        #discount: 0.99
        #use_gae: False
        #use_cuda: False
        #gae_tau: 0.95
        #entropy_weight: 0.01
        #gradient_clip: 5
        #optimization_epochs: 10
        #mini_batch_size: 256
        #ppo_ratio_clip: 0.2
        #learning_rate: 3.0e-4
        #adam_eps: 1.0e-5
        #horizon: 128
        #phi_arch: 'MLP'
        #actor_arch: 'None'
        #critic_arch: 'None'

        <<: *ppo_NatureCNN_graclip05_b32_h512_lr14_obs84
        #horizon: 128

    ppo_NatureCNN_graclip05_b32_h512_lr34_obs84_2actors:
        #discount: 0.99
        #use_gae: False
        #use_cuda: False
        #gae_tau: 0.95
        #entropy_weight: 0.01
        #gradient_clip: 5
        #optimization_epochs: 10
        #mini_batch_size: 256
        #ppo_ratio_clip: 0.2
        #learning_rate: 3.0e-4
        #adam_eps: 1.0e-5
        #horizon: 128
        #phi_arch: 'MLP'
        #actor_arch: 'None'
        #critic_arch: 'None'

        <<: *ppo_NatureCNN_graclip05_b32_h512_lr14_obs84
        learning_rate: 3.0e-4

    ppo_NatureCNN_graclip05_b32_h512_lr14_obs64_2actors:
        #discount: 0.99
        #use_gae: False
        #use_cuda: False
        #gae_tau: 0.95
        #entropy_weight: 0.01
        #gradient_clip: 5
        #optimization_epochs: 10
        #mini_batch_size: 256
        #ppo_ratio_clip: 0.2
        #learning_rate: 3.0e-4
        #adam_eps: 1.0e-5
        #horizon: 128
        #phi_arch: 'MLP'
        #actor_arch: 'None'
        #critic_arch: 'None'

        <<: *ppo_NatureCNN_graclip05_b32_h512_lr14_obs84
        observation_resize_dim: 64

    ppo_NatureCNN_graclip05_ent02_b32_h256_lr14_obs84_4actors:
        #discount: 0.99
        #use_gae: False
        #use_cuda: False
        #gae_tau: 0.95
        #entropy_weight: 0.01
        #gradient_clip: 5
        #optimization_epochs: 10
        #mini_batch_size: 256
        #ppo_ratio_clip: 0.2
        #learning_rate: 3.0e-4
        #adam_eps: 1.0e-5
        #horizon: 128
        #phi_arch: 'MLP'
        #actor_arch: 'None'
        #critic_arch: 'None'

        <<: *ppo_NatureCNN_graclip05_b32_h512_lr14_obs84
        #learning_rate: 3.0e-4
        entropy_weight: 0.2
        nbr_actors: 4
        horizon: 256

    ppo_NatureCNN_graclip05_ent002_gae099_b32_h128_lr14_obs84_8actors:
        #discount: 0.99
        #use_gae: False
        #use_cuda: False
        #gae_tau: 0.95
        #entropy_weight: 0.01
        #gradient_clip: 5
        #optimization_epochs: 10
        #mini_batch_size: 256
        #ppo_ratio_clip: 0.2
        #learning_rate: 3.0e-4
        #adam_eps: 1.0e-5
        #horizon: 128
        #phi_arch: 'MLP'
        #actor_arch: 'None'
        #critic_arch: 'None'

        <<: *ppo_NatureCNN_graclip05_b32_h512_lr14_obs84
        #learning_rate: 3.0e-4
        entropy_weight: 0.02
        gae_tau: 0.99
        nbr_actors: 8
        horizon: 128

    ppo_Nature64CNN_graclip05_ent002_gae099_b32_h128_lr14_obs84_16actors:
        #discount: 0.99
        #use_gae: False
        #use_cuda: False
        #gae_tau: 0.95
        #entropy_weight: 0.01
        #gradient_clip: 5
        #optimization_epochs: 10
        #mini_batch_size: 256
        #ppo_ratio_clip: 0.2
        #learning_rate: 3.0e-4
        #adam_eps: 1.0e-5
        #horizon: 128
        #phi_arch: 'MLP'
        #actor_arch: 'None'
        #critic_arch: 'None'

        <<: *ppo_NatureCNN_graclip05_b32_h512_lr14_obs84
        #learning_rate: 3.0e-4
        entropy_weight: 0.02
        gae_tau: 0.99
        nbr_actors: 16
        horizon: 128

    ppo_NatureCNN_graclip05_b128_h512_lr14_obs64_2actors:
        #discount: 0.99
        #use_gae: False
        #use_cuda: False
        #gae_tau: 0.95
        #entropy_weight: 0.01
        #gradient_clip: 5
        #optimization_epochs: 10
        #mini_batch_size: 256
        #ppo_ratio_clip: 0.2
        #learning_rate: 3.0e-4
        #adam_eps: 1.0e-5
        #horizon: 128
        #phi_arch: 'MLP'
        #actor_arch: 'None'
        #critic_arch: 'None'

        <<: *ppo_NatureCNN_graclip05_b32_h512_lr14_obs84
        mini_batch_size: 128
        #learning_rate: 3.0e-4
        observation_resize_dim: 64
        nbr_actors: 2
    
    ppo_paper_8actors_NoNormR:
        <<: *ppo_DQNCNN_graclip05_ep3_b32_h128_lr254_obs84
        nbr_actors: 8

    ppo_midloopOldPred_paper_ep3_clip0.1_gradclip0.5_b32_lr2.5e-4_ent0.02_8actors_NoNormR_Sk1:
        <<: *ppo_DQNCNN_graclip05_ep3_b32_h128_lr254_obs84
        nbr_actors: 8
        ppo_ratio_clip: 0.1
        entropy_weight: 0.02
        horizon: 128
        learning_rate: 2.5e-4
        mini_batch_size: 32
        optimization_epochs: 3
        gradient_clip: 0.5

    ppo_paper_b256_8actors_NoNormR:
        <<: *ppo_DQNCNN_graclip05_ep3_b32_h128_lr254_obs84
        nbr_actors: 8
        mini_batch_size: 256

    ppo_paper_b256_8actors:
        <<: *ppo_DQNCNN_graclip05_ep3_b32_h128_lr254_obs84
        nbr_actors: 8
        mini_batch_size: 256